import { NextResponse } from "next/server";

const vendors = [
  {
    id: "V-001",
    name: "Haven Furnished Suites",
    type: "Housing",
    city: "Rochester",
    state: "MN",
    rating: 4.9,
    reviews: 142,
    price: 1450,
    priceUnit: "month",
    verified: true,
    featured: true,
    distanceToFacility: "1.2 mi",
    features: ["Furnished", "Utilities Included", "Pet-Friendly", "Washer/Dryer"],
    description: "Premium furnished apartments steps from Mayo Clinic. All-inclusive pricing with flexible lease terms for traveling professionals.",
    contactEmail: "bookings@havensuites.com",
    contactPhone: "(507) 555-0142",
    availability: "Available Now",
    image: null,
  },
  {
    id: "V-002",
    name: "Midtown Corporate Living",
    type: "Housing",
    city: "New York",
    state: "NY",
    rating: 4.7,
    reviews: 98,
    price: 2800,
    priceUnit: "month",
    verified: true,
    featured: true,
    distanceToFacility: "0.8 mi",
    features: ["Furnished", "Doorman", "Gym Access", "Rooftop"],
    description: "Luxury corporate apartments in Midtown Manhattan. Walking distance to major hospital systems.",
    contactEmail: "leasing@midtowncorp.com",
    contactPhone: "(212) 555-0198",
    availability: "Available Jun 1",
    image: null,
  },
  {
    id: "V-003",
    name: "Lakeside Extended Stay",
    type: "Housing",
    city: "Cleveland",
    state: "OH",
    rating: 4.5,
    reviews: 67,
    price: 950,
    priceUnit: "month",
    verified: true,
    featured: false,
    distanceToFacility: "3.1 mi",
    features: ["Furnished", "Parking", "Kitchen", "Laundry"],
    description: "Comfortable extended stay apartments near Cleveland Clinic. Affordable monthly rates with no long-term commitment.",
    contactEmail: "info@lakesidestay.com",
    contactPhone: "(216) 555-0234",
    availability: "Available Now",
    image: null,
  },
  {
    id: "V-004",
    name: "SkyBridge Travel Services",
    type: "Travel",
    city: "Dallas",
    state: "TX",
    rating: 4.8,
    reviews: 213,
    price: 350,
    priceUnit: "booking",
    verified: true,
    featured: true,
    distanceToFacility: null,
    features: ["Flight Booking", "Hotel Packages", "24/7 Support", "Group Discounts"],
    description: "Full-service travel agency specializing in healthcare professional relocations. Negotiated rates with major airlines.",
    contactEmail: "travel@skybridge.com",
    contactPhone: "(214) 555-0312",
    availability: "Always Available",
    image: null,
  },
  {
    id: "V-005",
    name: "Metro Auto Rentals",
    type: "Car Rental",
    city: "Los Angeles",
    state: "CA",
    rating: 4.6,
    reviews: 89,
    price: 42,
    priceUnit: "day",
    verified: true,
    featured: false,
    distanceToFacility: "2.5 mi",
    features: ["Free Mileage", "Insurance Included", "Airport Pickup", "Monthly Rates"],
    description: "Reliable vehicle rentals with special long-term rates for traveling professionals. Fleet includes sedans, SUVs, and minivans.",
    contactEmail: "rentals@metroauto.com",
    contactPhone: "(310) 555-0456",
    availability: "Available Now",
    image: null,
  },
  {
    id: "V-006",
    name: "Sunrise Apartments",
    type: "Housing",
    city: "Phoenix",
    state: "AZ",
    rating: 4.4,
    reviews: 53,
    price: 1100,
    priceUnit: "month",
    verified: false,
    featured: false,
    distanceToFacility: "4.2 mi",
    features: ["Furnished", "Pool", "Parking", "Gated Community"],
    description: "Modern apartments in a quiet gated community. Ideal for healthcare professionals on 13-week assignments.",
    contactEmail: "leasing@sunriseapts.com",
    contactPhone: "(480) 555-0567",
    availability: "Available Jul 1",
    image: null,
  },
  {
    id: "V-007",
    name: "NorthStar Mobility",
    type: "Car Rental",
    city: "Chicago",
    state: "IL",
    rating: 4.3,
    reviews: 41,
    price: 38,
    priceUnit: "day",
    verified: true,
    featured: false,
    distanceToFacility: null,
    features: ["Flexible Terms", "Roadside Assistance", "GPS Included", "Weekly Discounts"],
    description: "Flexible car rental solutions tailored for travel nurses and allied health professionals.",
    contactEmail: "fleet@northstarmobility.com",
    contactPhone: "(312) 555-0678",
    availability: "Available Now",
    image: null,
  },
  {
    id: "V-008",
    name: "Pacific Coast Housing",
    type: "Housing",
    city: "San Francisco",
    state: "CA",
    rating: 4.8,
    reviews: 116,
    price: 2200,
    priceUnit: "month",
    verified: true,
    featured: false,
    distanceToFacility: "1.5 mi",
    features: ["Furnished", "City View", "Transit Access", "Co-Working Space"],
    description: "Contemporary furnished studios and one-bedrooms near UCSF Medical Center. Transit-friendly location.",
    contactEmail: "hello@pacificcoasthousing.com",
    contactPhone: "(415) 555-0789",
    availability: "Available Now",
    image: null,
  },
];

export async function GET() {
  return NextResponse.json({ success: true, data: vendors });
}

export async function POST(request: Request) {
  const body = await request.json();
  const newVendor = {
    id: `V-${String(vendors.length + 1).padStart(3, "0")}`,
    ...body,
    rating: 0,
    reviews: 0,
    verified: false,
    featured: false,
    createdAt: new Date().toISOString(),
  };
  return NextResponse.json({ success: true, data: newVendor }, { status: 201 });
}
