import { NextResponse } from "next/server";

const candidates = [
  {
    id: "C-001",
    name: "Sarah Mitchell",
    email: "s.mitchell@email.com",
    phone: "(555) 234-5678",
    specialty: "ICU Nursing",
    licenseState: "MN",
    yearsExperience: 6,
    status: "Active",
    currentAssignment: "Mayo Clinic - Rochester",
    startDate: "2026-06-02",
    profileComplete: true,
    rating: 4.9,
  },
  {
    id: "C-002",
    name: "Marcus Johnson",
    email: "m.johnson@email.com",
    phone: "(555) 345-6789",
    specialty: "Operating Room",
    licenseState: "OH",
    yearsExperience: 4,
    status: "Active",
    currentAssignment: "Cleveland Clinic",
    startDate: "2026-06-09",
    profileComplete: true,
    rating: 4.7,
  },
  {
    id: "C-003",
    name: "Emily Chen",
    email: "e.chen@email.com",
    phone: "(555) 456-7890",
    specialty: "Physical Therapy",
    licenseState: "MD",
    yearsExperience: 8,
    status: "Active",
    currentAssignment: "Johns Hopkins",
    startDate: "2026-05-26",
    profileComplete: false,
    rating: 4.8,
  },
  {
    id: "C-004",
    name: "Robert Taylor",
    email: "r.taylor@email.com",
    phone: "(555) 567-8901",
    specialty: "Emergency Medicine",
    licenseState: "CA",
    yearsExperience: 10,
    status: "Active",
    currentAssignment: "Cedars-Sinai",
    startDate: "2026-06-16",
    profileComplete: true,
    rating: 4.9,
  },
  {
    id: "C-005",
    name: "Lisa Rodriguez",
    email: "l.rodriguez@email.com",
    phone: "(555) 678-9012",
    specialty: "Med-Surg",
    licenseState: "MA",
    yearsExperience: 3,
    status: "At Risk",
    currentAssignment: "Mass General",
    startDate: "2026-05-19",
    profileComplete: false,
    rating: 4.5,
  },
  {
    id: "C-006",
    name: "David Park",
    email: "d.park@email.com",
    phone: "(555) 789-0123",
    specialty: "Respiratory Therapy",
    licenseState: "CA",
    yearsExperience: 5,
    status: "Active",
    currentAssignment: "Stanford Health",
    startDate: "2026-06-23",
    profileComplete: true,
    rating: 4.6,
  },
  {
    id: "C-007",
    name: "Amanda Foster",
    email: "a.foster@email.com",
    phone: "(555) 890-1234",
    specialty: "Labor & Delivery",
    licenseState: "NY",
    yearsExperience: 7,
    status: "Active",
    currentAssignment: "NYU Langone",
    startDate: "2026-06-02",
    profileComplete: true,
    rating: 5.0,
  },
  {
    id: "C-008",
    name: "Nicole Adams",
    email: "n.adams@email.com",
    phone: "(555) 901-2345",
    specialty: "NICU",
    licenseState: "PA",
    yearsExperience: 2,
    status: "Critical",
    currentAssignment: "Children's Hospital Philadelphia",
    startDate: "2026-05-22",
    profileComplete: false,
    rating: 4.4,
  },
];

export async function GET() {
  return NextResponse.json({ success: true, data: candidates });
}

export async function POST(request: Request) {
  const body = await request.json();
  const newCandidate = {
    id: `C-${String(candidates.length + 1).padStart(3, "0")}`,
    ...body,
    status: "Active",
    profileComplete: false,
    rating: 0,
    createdAt: new Date().toISOString(),
  };
  return NextResponse.json({ success: true, data: newCandidate }, { status: 201 });
}
