import { NextResponse } from "next/server";

const assignments = [
  {
    id: "AL-001",
    candidateName: "Sarah Mitchell",
    candidateAvatar: "SM",
    role: "ICU Nurse (RN)",
    facility: "Mayo Clinic - Rochester",
    startDate: "2026-06-02",
    housingStatus: "Confirmed",
    travelStatus: "Booked",
    documentsStatus: "Complete",
    readiness: 95,
    riskScore: 2,
    riskLevel: "Low",
    actionNeeded: "Final walkthrough scheduled",
    checklist: [
      { item: "Background check", status: "Complete" },
      { item: "Drug screening", status: "Complete" },
      { item: "License verification", status: "Complete" },
      { item: "Housing confirmed", status: "Complete" },
      { item: "Travel booked", status: "Complete" },
      { item: "Orientation materials sent", status: "Pending" },
    ],
  },
  {
    id: "AL-002",
    candidateName: "Marcus Johnson",
    candidateAvatar: "MJ",
    role: "OR Tech",
    facility: "Cleveland Clinic",
    startDate: "2026-06-09",
    housingStatus: "Pending",
    travelStatus: "Booked",
    documentsStatus: "Complete",
    readiness: 72,
    riskScore: 5,
    riskLevel: "Medium",
    actionNeeded: "Housing confirmation needed",
    checklist: [
      { item: "Background check", status: "Complete" },
      { item: "Drug screening", status: "Complete" },
      { item: "License verification", status: "Complete" },
      { item: "Housing confirmed", status: "Pending" },
      { item: "Travel booked", status: "Complete" },
      { item: "Orientation materials sent", status: "Not Started" },
    ],
  },
  {
    id: "AL-003",
    candidateName: "Emily Chen",
    candidateAvatar: "EC",
    role: "Physical Therapist",
    facility: "Johns Hopkins",
    startDate: "2026-05-26",
    housingStatus: "Confirmed",
    travelStatus: "Pending",
    documentsStatus: "Incomplete",
    readiness: 58,
    riskScore: 7,
    riskLevel: "High",
    actionNeeded: "Missing certifications & travel",
    checklist: [
      { item: "Background check", status: "Complete" },
      { item: "Drug screening", status: "Complete" },
      { item: "License verification", status: "Pending" },
      { item: "Housing confirmed", status: "Complete" },
      { item: "Travel booked", status: "Not Started" },
      { item: "Orientation materials sent", status: "Not Started" },
    ],
  },
  {
    id: "AL-004",
    candidateName: "Robert Taylor",
    candidateAvatar: "RT",
    role: "ER Nurse (RN)",
    facility: "Cedars-Sinai",
    startDate: "2026-06-16",
    housingStatus: "Confirmed",
    travelStatus: "Booked",
    documentsStatus: "Complete",
    readiness: 88,
    riskScore: 3,
    riskLevel: "Low",
    actionNeeded: "Awaiting facility badge",
    checklist: [
      { item: "Background check", status: "Complete" },
      { item: "Drug screening", status: "Complete" },
      { item: "License verification", status: "Complete" },
      { item: "Housing confirmed", status: "Complete" },
      { item: "Travel booked", status: "Complete" },
      { item: "Orientation materials sent", status: "Pending" },
    ],
  },
  {
    id: "AL-005",
    candidateName: "Lisa Rodriguez",
    candidateAvatar: "LR",
    role: "Med-Surg RN",
    facility: "Mass General",
    startDate: "2026-05-19",
    housingStatus: "Not Started",
    travelStatus: "Not Started",
    documentsStatus: "Missing",
    readiness: 22,
    riskScore: 9,
    riskLevel: "Critical",
    actionNeeded: "Urgent: All logistics pending",
    checklist: [
      { item: "Background check", status: "Complete" },
      { item: "Drug screening", status: "Pending" },
      { item: "License verification", status: "Pending" },
      { item: "Housing confirmed", status: "Not Started" },
      { item: "Travel booked", status: "Not Started" },
      { item: "Orientation materials sent", status: "Not Started" },
    ],
  },
  {
    id: "AL-006",
    candidateName: "David Park",
    candidateAvatar: "DP",
    role: "Respiratory Therapist",
    facility: "Stanford Health",
    startDate: "2026-06-23",
    housingStatus: "Pending",
    travelStatus: "Pending",
    documentsStatus: "Incomplete",
    readiness: 45,
    riskScore: 6,
    riskLevel: "Medium",
    actionNeeded: "Documents & housing follow-up",
    checklist: [
      { item: "Background check", status: "Complete" },
      { item: "Drug screening", status: "Complete" },
      { item: "License verification", status: "Pending" },
      { item: "Housing confirmed", status: "Pending" },
      { item: "Travel booked", status: "Pending" },
      { item: "Orientation materials sent", status: "Not Started" },
    ],
  },
  {
    id: "AL-007",
    candidateName: "Amanda Foster",
    candidateAvatar: "AF",
    role: "L&D Nurse (RN)",
    facility: "NYU Langone",
    startDate: "2026-06-02",
    housingStatus: "Confirmed",
    travelStatus: "Booked",
    documentsStatus: "Complete",
    readiness: 100,
    riskScore: 1,
    riskLevel: "Low",
    actionNeeded: "Ready — no action needed",
    checklist: [
      { item: "Background check", status: "Complete" },
      { item: "Drug screening", status: "Complete" },
      { item: "License verification", status: "Complete" },
      { item: "Housing confirmed", status: "Complete" },
      { item: "Travel booked", status: "Complete" },
      { item: "Orientation materials sent", status: "Complete" },
    ],
  },
  {
    id: "AL-008",
    candidateName: "James Wilson",
    candidateAvatar: "JW",
    role: "Cath Lab Tech",
    facility: "Texas Medical Center",
    startDate: "2026-06-30",
    housingStatus: "Pending",
    travelStatus: "Pending",
    documentsStatus: "Complete",
    readiness: 65,
    riskScore: 4,
    riskLevel: "Medium",
    actionNeeded: "Housing options under review",
    checklist: [
      { item: "Background check", status: "Complete" },
      { item: "Drug screening", status: "Complete" },
      { item: "License verification", status: "Complete" },
      { item: "Housing confirmed", status: "Pending" },
      { item: "Travel booked", status: "Pending" },
      { item: "Orientation materials sent", status: "Not Started" },
    ],
  },
  {
    id: "AL-009",
    candidateName: "Nicole Adams",
    candidateAvatar: "NA",
    role: "NICU Nurse (RN)",
    facility: "Children's Hospital Philadelphia",
    startDate: "2026-05-22",
    housingStatus: "Not Started",
    travelStatus: "Pending",
    documentsStatus: "Missing",
    readiness: 18,
    riskScore: 10,
    riskLevel: "Critical",
    actionNeeded: "Escalate: Start date in 14 days",
    checklist: [
      { item: "Background check", status: "Complete" },
      { item: "Drug screening", status: "Pending" },
      { item: "License verification", status: "Not Started" },
      { item: "Housing confirmed", status: "Not Started" },
      { item: "Travel booked", status: "Not Started" },
      { item: "Orientation materials sent", status: "Not Started" },
    ],
  },
  {
    id: "AL-010",
    candidateName: "Kevin O'Brien",
    candidateAvatar: "KO",
    role: "Radiology Tech",
    facility: "Emory Healthcare",
    startDate: "2026-06-09",
    housingStatus: "Confirmed",
    travelStatus: "Booked",
    documentsStatus: "Complete",
    readiness: 92,
    riskScore: 2,
    riskLevel: "Low",
    actionNeeded: "Confirm parking pass",
    checklist: [
      { item: "Background check", status: "Complete" },
      { item: "Drug screening", status: "Complete" },
      { item: "License verification", status: "Complete" },
      { item: "Housing confirmed", status: "Complete" },
      { item: "Travel booked", status: "Complete" },
      { item: "Orientation materials sent", status: "Pending" },
    ],
  },
  {
    id: "AL-011",
    candidateName: "Priya Sharma",
    candidateAvatar: "PS",
    role: "Telemetry RN",
    facility: "Northwestern Memorial",
    startDate: "2026-06-16",
    housingStatus: "Confirmed",
    travelStatus: "Pending",
    documentsStatus: "Incomplete",
    readiness: 70,
    riskScore: 5,
    riskLevel: "Medium",
    actionNeeded: "BLS certification expiring",
    checklist: [
      { item: "Background check", status: "Complete" },
      { item: "Drug screening", status: "Complete" },
      { item: "License verification", status: "Complete" },
      { item: "Housing confirmed", status: "Complete" },
      { item: "Travel booked", status: "Pending" },
      { item: "Orientation materials sent", status: "Not Started" },
    ],
  },
  {
    id: "AL-012",
    candidateName: "Carlos Mendez",
    candidateAvatar: "CM",
    role: "Surgical Tech",
    facility: "UCSF Medical Center",
    startDate: "2026-06-23",
    housingStatus: "Confirmed",
    travelStatus: "Booked",
    documentsStatus: "Complete",
    readiness: 85,
    riskScore: 3,
    riskLevel: "Low",
    actionNeeded: "Send welcome packet",
    checklist: [
      { item: "Background check", status: "Complete" },
      { item: "Drug screening", status: "Complete" },
      { item: "License verification", status: "Complete" },
      { item: "Housing confirmed", status: "Complete" },
      { item: "Travel booked", status: "Complete" },
      { item: "Orientation materials sent", status: "Pending" },
    ],
  },
];

export async function GET() {
  return NextResponse.json({ success: true, data: assignments });
}

export async function POST(request: Request) {
  const body = await request.json();
  const updated = {
    ...body,
    updatedAt: new Date().toISOString(),
  };
  return NextResponse.json({ success: true, data: updated });
}
